version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "8090:8090"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app_network
  db:
    platform: linux/x86_64
    image: mysql:5.6.47
    container_name: app-db
    ports:
      - "3306:3306"
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - app_network
  php:
    container_name: php
    image: php:8.1-fpm
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

#Переопределить сервис базы данных на mysql 8 не меняя текущий файл
#
# 1) Удалить контейнер app-db
# 2) Выполнить комманду docker run --name=app-db \
#--mount type=bind,src=./etc/infrastructure/mysql/my.cnf,dst=/etc/mysql/my.cnf \
#--mount type=bind,src=./etc/database/base.sql,dst=/docker-entrypoint-initdb.d/base.sql \
#-d mysql/mysql-server:8.0
